defaultSemverRangePrefix: ""

enableTelemetry: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

packageExtensions:
  "node-cache@*":
    dependencies:
      "@types/node": "*"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
