defaultSemverRangePrefix: ""

enableTelemetry: false

packageExtensions:
  node-cache@*:
    dependencies:
      "@types/node": "*"
  ovsx@*:
    dependencies:
      semver: "*"
  tailwindcss@*:
    peerDependenciesMeta:
      autoprefixer:
        optional: true

yarnPath: .yarn/releases/yarn-3.2.0-rc.8.cjs
