defaultSemverRangePrefix: ""

enableTelemetry: false

packageExtensions:
  node-cache@*:
    dependencies:
      "@types/node": "*"
  ovsx@*:
    dependencies:
      semver: "*"
      tmp: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-sources.cjs
