[target.aarch64-unknown-linux-gnu]
image = "cross/aarch64:v1"

[target.aarch64-unknown-linux-gnu.env]
passthrough = ["RUSTFLAGS"]

[target.armv7-unknown-linux-gnueabihf]
image = "cross/armv7:v1"

[target.armv7-unknown-linux-gnueabihf.env]
passthrough = ["RUSTFLAGS"]
