[package]
name = "cloudmusic-wasm"
version = "0.1.0"
authors = ["YXL <chenxin.lan.76@gmail.com>"]
edition = "2018"

[lib]
crate-type = ['cdylib']

[dependencies]
wasm-bindgen = "0.2"

[dependencies.rodio]
git = "https://github.com/RustAudio/rodio"
branch = "master"
default-features = false
features = ["flac", "symphonia-mp3", "wasm-bindgen"]

[target."cfg(debug_assertions)".dependencies]
console_error_panic_hook = "0.1"
