name: Build

on:
  push:
    paths:
      - "crates/*"
      - "packages/*"
      - "Cargo.*"
      - ".github/workflows/build.yml"
    branches:
      - master
      - dev

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            target: aarch64-pc-windows-msvc

    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Installing needed Ubuntu dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
          sudo apt-get install -y libx11-dev

      - name: Install LLVM and Clang
        if: runner.os == 'Windows'
        uses: KyleMayes/install-llvm-action@v1.2.2
        with:
          version: "11"
          directory: ${{ runner.temp }}/llvm

      - name: Install rust target
        run: rustup target add ${{ matrix.target }}

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2.1.5
        id: cargo-cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build x86-64
        if: runner.os != 'Windows'
        run: cargo build --release

      - name: Build x86-64
        if: runner.os == 'Windows'
        run: cargo build --release
        env:
          LIBCLANG_PATH: ${{ runner.temp }}/llvm/bin

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-x86-64
          path: crates/native/index.node
      
      - uses: actions-rs/cargo@v1
        name: Build aarch64
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-aarch64
          path: crates/native/index.node
